- name: variables from task
  hosts: localhost
  tasks:
   - name: print the information
     vars:
      Course: "Course"
      Purpose: "Interview"
     ansible;builtin.debug:
      msg: "Hi I ' am practicing {{Course}} for my {{Purpose}}."
