- name: variables from task
  hosts: localhost
  vars:
   Course: "Shellscript"
   Purpose: "Interview"
#it will overide first
  tasks:
   - name: print override information
     vars:
      Course: "DevOps"
      Purpose: "Interview"
     ansible.builtin.debug:
      msg: "Hi I ' am practicing {{Course}} for my {{Purpose}}."
#It will exceute second
  tasks:
   - name: print the information
     ansible.builtin.debug:
      msg: "Hi iam practing {{Course}} for my {{Purpose}}."