- name: Variables from Task
  hosts: localhost
  vars:
   Course: "Devops"
   Reason: "Interview"
  tasks:
   - name: print the information
     vars:
      Course: "Devops"
      Reason: "Interview"
     ansible.builtin.debug:
      msg: "Hi I am practicing {{Course}} for my {{Reason}}."
