- name: Variables from files
  hosts: loacalhost
  var_file:
   - var.yaml
  tasks:
   - name: print the inormation
     ansible.builtin.debug:
      msg: "Im practicing {{Course}} for my {{Interview}}."