- name: Variables from files
  hosts: localhost
  vars_file:
   - vars.yaml
  tasks:
   - name: print the information
     ansible.builtin.debug:
      msg: "Im practicing {{Course}} for my {{Purpose}}."



