- name: Variables from files
  hosts: localhost
  vars_files:
   - vars.yaml
  tasks:
    - name: print the information
      # vars_files:
      #   - vars.yaml
      ansible.builtin.debug:
        msg: Im practicing {{Course}} for my {{Purpose}}.



