- name: variables from promt
  hosts: localhost
  vars_prompt:
   - name: USERNAME
     prompt: Please enter the username
     private: fales
   - name: PASSWORD
     prompt: please enter the password
     private: true
  tasks:
    - name: print the information
      ansible.builtin.debug:
       msg: "Hi Enther the user name: {{USERNAME}} password:{{PASSWORD}}"    

