- name: variables from inventory
  hosts: localhost
  tasks:
   - name: print the information
     vars:
      Learn: "Inventory"
      Where: "Ansible"
     ansible.builtin.debug:
      msg: "Hi I am executing {{Learn}} variables in {{Where}}"
      