- name: variables from promt2
  hosts: localhost
  vars_files:
   vars.yaml
  tasks:
   - name: print the information
     ansible.builtin.debug:
      msg: "Hello I am practicing {{Cours}} for my {{Purpose}}" 