- name: check number
  hosts: localhost
  vars_prompt:
   - name: number
     prompt: enter number
     private: no
  tasks:
    - name: number is less than 10.9
      ansible.builtin.debug:
       msg: "Given number {{number}} is less than 10.9"
      when: number | float < 10.9
    - name: number is greater than 10.9
      ansible.builtin.debug:
       msg: "Given number {{number}} is greater than 10.9"  
      when: number | float >=10.9
