- name: default value
  hosts: localhost
  tasks:
   - name: print default value
     ansible.builtin.debug:
      msg: "Hello, {{Course | default ('Ansible')}}"
- name: Upper case
  hosts: localhost
  vars:
   greeting: "Hello, Good Bye"
  tasks:
   - name: Convert into Uppercase 
     ansible.builtin.debug:
       msg: "Hello {{greeting | upper}}"
   - name: Convert into Lower
     vars:
      greeting: "Hello, Good Moon"
     ansible.builtin.debug:
      msg: "{{greeting |lower}}" 
   - name: remove duplicates
     vars:
      number: {1,2,3,4,3,5,2,1}  
     tasks:
      - name: remove duplicates
        ansible.builtin.debug:
         msg: "{{number | unique}}" 