- name: default value
  hosts: localhost
  vars:
   greeting: "Hello Good Sun"
  tasks:
   - name: print default value
     ansible.builtin.debug:
      msg: "Hello, {{Course | default ('Ansible')}}"
   - name: print upper case
     ansible.builtin.debug:
      msg: "{{greeting | upper}}"  
   - name: print lower case
     ansible.builtin.debug:
      msg: "{{greeting | lower}}"
   - name: remove duplicates
     ansible.builtin.debug:
- name: remove duplicates
  hosts: localhost
  vars:
   number: [1,2,1,4,1,5,2,33,3]
  tasks:
   - name: remove duplicate
     ansible.builtin.debug:
      msg: "{{number | unique}}"
- name: print min & max
  hosts: localhost
  vars:
   ages: [12,23,0,1000]    
  tasks:
   - name: print min and max ages
     ansible.builtin.debug:
      msg: " min age: {{ ages | min }}, max age: {{ ages | max }} "  
      #msg: " min age: {{ ages | min }}, max age: {{ ages | max }}"

 