- name: default value
  hosts: localhost
  tasks:
  vars:
   greeting: "Hello Good Sun"
   - name: print default value
     ansible.builtin.debug:
      msg: "Hello, {{Course | default ('Ansible')}}"
   - name: print upper case
     ansible.builtin.debug:
      msg: "{{greeting | upper}}"  
   - name: print lower case
     ansible.built.debug:
      msg: "{{greeting | lower}}"