- name: default value
  hosts: localhost
  tasks:
   - name: print default value
     ansible.builtin.debug:
      msg: "Hello, {{Course | default ('Ansible')}}"
- name: Upper case
  hosts: localhost
  vars:
   greeting: "Hello, Good Bye"
  tasks:
   - name: Convert into Uppercase 
     ansible.builtin.debug:
       msg: "Hello {{greeting | upper}}"