- name: loops
  hosts: localhost
  tasks:
   - name: print names
     ansible.builtin.debug:
      msg: " Hello {{item}}"
     loop:
      - Linux
      - Shell
      - Ansible
 - name: install packages
   hosts: Web
   tasks:
    - name: install packages
      ansible.builtin.dnf:
       - name: "{{item}}"
         state: latest
      loop: 
       - mysql
       - nginx
       - postfix 


